#!/bin/bash

#

read -r -p "domainmu: " awalsekali
read -r -p "token cfmu: " tokencf

export CF_Token="${tokencf}"

cat >/root/domain <<EOF
${awalsekali}
EOF

mkdir -p /etc/xray
cat >/etc/xray/domain <<EOF
${awalsekali}
EOF

cd

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
 
#update
apt update -y
apt upgrade -y
apt dist-upgrade -y
apt install socat netfilter-persistent -y
apt install vnstat lsof fail2ban -y
apt install curl sudo neofetch -y
apt -y install wget
apt -y install net-tools
mkdir /user >> /dev/null 2>&1
mkdir /tmp >> /dev/null 2>&1

#DNS
#cat > /etc/systemd/resolved.conf << END
#[Resolve]
#DNS=1.1.1.1 1.0.0.1
#Domains=~.
#ReadEtcHosts=yes
#END
#systemctl enable resolvconf
#systemctl enable systemd-resolved
#systemctl enable NetworkManager
#rm -rf /etc/resolv.conf
#rm -rf /etc/resolvconf/resolv.conf.d/head
#echo "
#nameserver 127.0.0.53
#" >> /etc/resolv.conf
#echo "
#" >> /etc/resolvconf/resolv.conf.d/head
#systemctl restart resolvconf
#systemctl restart systemd-resolved
#systemctl restart NetworkManager
#wget -O /usr/bin/changedns https://raw.githubusercontent.com/fferry98/xray-443-80/main/changedns
#chmod +x /usr/bin/changedns

echo "clear" >> .profile
echo "neofetch" >> .profile

# install webserver
apt -y install nginx
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default

cat >/etc/nginx/nginx.conf <<EOF
user www-data;

worker_processes 1;
pid /var/run/nginx.pid;

events {
	multi_accept on;
  worker_connections 1024;
}

http {
	gzip on;
	gzip_vary on;
	gzip_comp_level 5;
	gzip_types    text/plain application/x-javascript text/javascript application/octet-stream text/xml text/css application/protobuf application/vnd.android.package-archive application/binary application/zip application/json application/javascript application/x-www-form-urlencoded application/geo+json application/manifest+json application/x-web-app-manifest+json text/cache-manifest text/x-component text/x-cross-domain-policy;

	autoindex on;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  charset UTF-8;
  source_charset UTF-8;
  charset_types text/plain application/octet-stream text/javascript application/json;
  keepalive_timeout 165;
  types_hash_max_size 2048;
  server_tokens off;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;
  client_max_body_size 32M;
	client_header_buffer_size 8m;
	large_client_header_buffers 8 8m;

	fastcgi_buffer_size 8m;
	fastcgi_buffers 10 8m;

	fastcgi_read_timeout 600;

	set_real_ip_from 204.93.240.0/24;
	set_real_ip_from 204.93.177.0/24;
	set_real_ip_from 199.27.128.0/21;
	set_real_ip_from 173.245.48.0/20;
	set_real_ip_from 103.21.244.0/22;
	set_real_ip_from 103.22.200.0/22;
	set_real_ip_from 103.31.4.0/22;
	set_real_ip_from 141.101.64.0/18;
	set_real_ip_from 108.162.192.0/18;
	set_real_ip_from 190.93.240.0/20;
	set_real_ip_from 188.114.96.0/20;
	set_real_ip_from 197.234.240.0/22;
	set_real_ip_from 198.41.128.0/17;
	real_ip_header     CF-Connecting-IP;

  include /etc/nginx/conf.d/*.conf;
  add_header 'Access-Control-Expose-Headers' 'Content-Lenght,Content-Range';
  add_header Strict-Transport-Security "max-age=999999999; includeSubDomains; preload";
}
EOF

cat >/etc/nginx/conf.d/vps.conf <<EOF
server {
  listen       89;
  server_name  127.0.0.1 localhost;
  access_log /var/log/nginx/vps-access.log;
  error_log /var/log/nginx/vps-error.log error;
  root   /home/vps/public_html;

  location /file/ {
    index  index.html index.htm index.php;
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_pass  127.0.0.1:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
  }
}
EOF


clear
red='\e[1;31m'
green='\e[0;32m'
yell='\e[1;33m'
NC='\e[0m'
echo "XRAY Core Vmess / Vless / Trojan / Shadowsocks"
echo "Trojan"
echo "Progress..."
sleep 3

domain=$(cat /root/domain)
sleep 1
mkdir -p /etc/xray 
sleep 1


# install xray
sleep 1
echo -e "[ ${green}INFO$NC ] Downloading & Installing xray core"
# Make Folder XRay
mkdir -p /etc/xray
# / / Ambil Xray Core Version Terbaru
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" - install -u www-data --beta

## crt xray
systemctl stop nginx
rm -rf /etc/nginx/conf.d/alone.conf

# nginx 
/etc/init.d/nginx stop

mkdir -p /home/vps/public_html

# set uuid
uuid=0fb7e2e4-99a5-4191-baf3-690c2e3b65a8
uuid1=1fb7e2e4-99a5-4191-baf3-690c2e3b65a8

# xray config
cat > /etc/xray/config.json << END
{
  "log" : {
    "loglevel": "none"
  },
  "inbounds": [
      {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    },
#inivmesshu
     {
     "listen": "127.0.0.1",
     "port": 31000,
     "protocol": "vmess",
      "settings": {
            "clients": [
               {
                 "id": "${uuid}",
                 "alterId": 0
             }
          ]
       },
       "streamSettings":{
         "network": "httpupgrade",
            "httpupgradeSettings": {
                "path": "/vmhu"
          }
        }
     },
#inivmessws
     {
     "listen": "127.0.0.1",
     "port": 31100,
     "protocol": "vmess",
      "settings": {
            "clients": [
               {
                 "id": "${uuid1}",
                 "alterId": 0
             }
          ]
       },
       "streamSettings":{
         "network": "ws",
            "wsSettings": {
                "path": "/vmws"
          }
        }
     }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "outboundTag": "blocked"
      },
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ]
      }
    ]
  },
  "stats": {},
  "api": {
    "services": [
      "StatsService"
    ],
    "tag": "api"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserDownlink": true,
        "statsUserUplink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink" : true,
      "statsOutboundDownlink" : true
    }
  }
}
END
rm -rf /etc/systemd/system/xray.service.d
cat <<EOF> /etc/systemd/system/xray.service
[Unit]
Description=Xray Service
Documentation=https://github.com/xtls
After=network.target nss-lookup.target

[Service]
User=www-data
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/xray run -config /etc/xray/config.json
Restart=on-failure
RestartPreventExitStatus=23
LimitNPROC=10000
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target

EOF

#nginx config
wget -O /etc/nginx/conf.d/xray.conf https://raw.githubusercontent.com/fferry98/xray-443-80/main/xray.conf

sleep 1
echo -e "$yell[SERVICE]$NC Restart All service"
systemctl daemon-reload
sleep 1
echo -e "[ ${green}ok${NC} ] Enable & restart xray "
systemctl enable xray
systemctl restart xray
systemctl restart nginx

sleep 1

#done
clear
#rm -f ins-xray.sh
rm -f install-xray.sh

cd

cd /root/
wget https://raw.githubusercontent.com/acmesh-official/acme.sh/master/acme.sh
bash acme.sh --install
wget -O $HOME/.acme.sh/dns_cf.sh https://raw.githubusercontent.com/acmesh-official/acme.sh/master/dnsapi/dns_cf.sh
chmod +x $HOME/.acme.sh/dns_cf.sh

domain=$(cat /root/domain)
"$HOME/.acme.sh/acme.sh" --issue --standalone -d ${domain} -d *.${domain} --dns dns_cf -k ec-256 --server letsencrypt --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key

systemctl restart nginx
systemctl restart xray

systemctl stop xray
systemctl start xray
systemctl stop apache2
systemctl restart nginx
systemctl start apache2
rm /home/vps/public_html/*
systemctl daemon-reload

echo "REBOOT ON 10 SECONDS"
sleep 10
reboot
